version: 2
updates:
  - package-ecosystem: 'nuget'
    directory: '/'  # Update packages in the root of your repository
    schedule:
      interval: "daily" 
    open-pull-requests-limit: 10 
    allow:
      - dependency-name: "*"
    ignore:
      - dependency-name: "FluentAssertions"
        versions: [">=8.0.0"]  # Ignore updates to FluentAssertions version 8.x.x or higher since that has a paid license
